In [1]:
import pandas as pd

In [2]:
# ----------------------------
# Paths
# ----------------------------
pval_path = "/scratch/gpfs/AMOELLER/diet_manip/AlleleFlux_mapq20/longitudinal/p_value_summary/pre_end-fat_control/p_value_summary_two_sample_paired_pre_end.tsv"
cog_path  = "/scratch/gpfs/AMOELLER/sidd/diet_manip/reCOGnizer_results.tsv"

In [3]:
# ----------------------------
# Load p-values summary
# ----------------------------
df_summary = pd.read_csv(pval_path, sep="\t")

# Optional: restrict to a single test type
df_summary = df_summary.loc[df_summary["test_type"].eq("two_sample_paired_tTest")].copy()
df_summary

,period,mag_id,contig,position,gene_id,test_type,min_p_value,source_file,q_value
0,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18893,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.214371,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.407921
1,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18917,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.224986,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.419240
2,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18896,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.183175,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.377877
3,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18941,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.733013,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.803778
4,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18932,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.398779,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.514322
...,...,...,...,...,...,...,...,...,...
1501421,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2314,SLG1207_DASTool_bins_18.fa_k141_95558_3,two_sample_paired_tTest,0.197400,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.390277
1501422,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2575,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.235670,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.430836
1501423,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2643,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.223203,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.417333
1501424,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,847,NaN,two_sample_paired_tTest,0.176519,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.374445
1501425,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2581,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.350617,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.466342

In [5]:
# ----------------------------
# Explode gene_id so it's ONE gene per row
# Handles cells like: "geneA ,geneB" or "geneA, geneB"
# ----------------------------
df_exploded = df_summary.copy()

# Make a list column from gene_id (robust to NaN)
gene_series = df_exploded["gene_id"].astype("string")

# Split on commas with optional whitespace around them
df_exploded["gene_id_single"] = gene_series.str.split(r"\s*,\s*")

# Explode into one row per gene
df_exploded = df_exploded.explode("gene_id_single", ignore_index=True)

# Clean whitespace; drop empties/NAs
df_exploded["gene_id_single"] = df_exploded["gene_id_single"].astype("string").str.strip()
df_exploded = df_exploded.loc[
    df_exploded["gene_id_single"].notna() & (df_exploded["gene_id_single"] != "")
].copy()

df_exploded

,period,mag_id,contig,position,gene_id,test_type,min_p_value,source_file,q_value,gene_id_single
0,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18893,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.214371,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.407921,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
1,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18917,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.224986,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.419240,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
2,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18896,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.183175,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.377877,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
3,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18941,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.733013,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.803778,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
4,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18932,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.398779,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.514322,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
...,...,...,...,...,...,...,...,...,...,...
394066,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2645,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.152674,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.356860,SLG1207_DASTool_bins_18.fa_k141_95558_4
394067,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2314,SLG1207_DASTool_bins_18.fa_k141_95558_3,two_sample_paired_tTest,0.197400,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.390277,SLG1207_DASTool_bins_18.fa_k141_95558_3
394068,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2575,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.235670,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.430836,SLG1207_DASTool_bins_18.fa_k141_95558_4
394069,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2643,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.223203,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.417333,SLG1207_DASTool_bins_18.fa_k141_95558_4
394071,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2581,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.350617,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.466342,SLG1207_DASTool_bins_18.fa_k141_95558_4

In [6]:
# ----------------------------
# Load + prep COG/reCOGnizer table (only needed cols)
# ----------------------------
usecols = ["qseqid", "Protein description", "DB description", "DB ID", "CDD ID", "General functional category", "Functional category"]
df_cog = pd.read_csv(cog_path, sep="\t", usecols=usecols)

# Extract gene_id from qseqid and normalize whitespace
df_cog["gene_id_single"] = (
    df_cog["qseqid"].astype("string").str.split("_#", n=1).str[0].str.strip()
)
df_cog

,qseqid,DB ID,Protein description,DB description,CDD ID,General functional category,Functional category,gene_id_single
0,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,COG1961,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,CDD:441564,INFORMATION STORAGE AND PROCESSING,"Replication, recombination and repair",SLG1007_DASTool_bins_35.fa_k141_102792_11
1,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,NF041201,NaN,fdxN element excision recombinase XisF.,CDD:469105,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
2,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,cd00338,NaN,"Serine Recombinase family, catalytic domain; a...",CDD:238206,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
3,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam00239,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",CDD:425548,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
4,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam07508,recombinase family protein,Recombinase. This domain is usually found asso...,CDD:429502,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
...,...,...,...,...,...,...,...,...
2680298,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,TIGR00521,bifunctional phosphopantothenoylcysteine decar...,phosphopantothenoylcysteine decarboxylase / ph...,CDD:273116,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_8
2680299,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam02441,Flavoprotein (Provisional),Flavoprotein. This family contains diverse fla...,CDD:426775,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_8
2680300,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam04127,DNA / pantothenate metabolism flavoprotein (Pr...,DNA / pantothenate metabolism flavoprotein. Th...,CDD:461186,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_8
2680301,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,COG4684,Uncharacterized membrane protein,Uncharacterized membrane protein [Function unk...,CDD:443720,POORLY CHARACTERIZED,Function unknown,SLG992_DASTool_bins_86.fa_k141_9710_9
2680302,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,pfam12822,ECF transporter S component,"ECF transporter, substrate-specific component....",CDD:432808,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_9

In [7]:
annot_cols = ["Protein description", "DB description", "DB ID", "CDD ID", "General functional category", "Functional category"]
placeholder = "-"  # or "" if you truly want blank, but "-" is clearer

# Fill missing values so comma-separated lists stay aligned
for c in annot_cols:
    df_cog[c] = df_cog[c].astype("string").fillna(placeholder)
    df_cog[c] = df_cog[c].replace("", placeholder)

df_cog

,qseqid,DB ID,Protein description,DB description,CDD ID,General functional category,Functional category,gene_id_single
0,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,COG1961,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,CDD:441564,INFORMATION STORAGE AND PROCESSING,"Replication, recombination and repair",SLG1007_DASTool_bins_35.fa_k141_102792_11
1,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,NF041201,-,fdxN element excision recombinase XisF.,CDD:469105,-,-,SLG1007_DASTool_bins_35.fa_k141_102792_11
2,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,cd00338,-,"Serine Recombinase family, catalytic domain; a...",CDD:238206,-,-,SLG1007_DASTool_bins_35.fa_k141_102792_11
3,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam00239,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",CDD:425548,-,-,SLG1007_DASTool_bins_35.fa_k141_102792_11
4,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam07508,recombinase family protein,Recombinase. This domain is usually found asso...,CDD:429502,-,-,SLG1007_DASTool_bins_35.fa_k141_102792_11
...,...,...,...,...,...,...,...,...
2680298,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,TIGR00521,bifunctional phosphopantothenoylcysteine decar...,phosphopantothenoylcysteine decarboxylase / ph...,CDD:273116,-,-,SLG992_DASTool_bins_86.fa_k141_9710_8
2680299,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam02441,Flavoprotein (Provisional),Flavoprotein. This family contains diverse fla...,CDD:426775,-,-,SLG992_DASTool_bins_86.fa_k141_9710_8
2680300,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam04127,DNA / pantothenate metabolism flavoprotein (Pr...,DNA / pantothenate metabolism flavoprotein. Th...,CDD:461186,-,-,SLG992_DASTool_bins_86.fa_k141_9710_8
2680301,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,COG4684,Uncharacterized membrane protein,Uncharacterized membrane protein [Function unk...,CDD:443720,POORLY CHARACTERIZED,Function unknown,SLG992_DASTool_bins_86.fa_k141_9710_9
2680302,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,pfam12822,ECF transporter S component,"ECF transporter, substrate-specific component....",CDD:432808,-,-,SLG992_DASTool_bins_86.fa_k141_9710_9

In [8]:
# Printing lines that are the exact duplicates
df_check = df_cog  # or df_cog_subset

dup_mask = df_check.duplicated(subset=["gene_id_single"] + annot_cols, keep=False)

dups = (
    df_check.loc[dup_mask, ["gene_id_single"] + annot_cols]
            .sort_values(["gene_id_single"] + annot_cols)
)

print(len(dups), "duplicate rows (including all copies)")
dups.head(n=20)

727956 duplicate rows (including all copies)

,gene_id_single,Protein description,DB description,DB ID,CDD ID,General functional category,Functional category
14,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250,-,-
15,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250,-,-
16,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250,-,-
17,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250,-,-
11,SLG1007_DASTool_bins_35.fa_k141_102792_14,Extracellular matrix glycoprotein Laminin subu...,"KOG0994, Extracellular matrix glycoprotein Lam...",KOG0994,CDD:228940,CELLULAR PROCESSES AND SIGNALING,Extracellular structures
12,SLG1007_DASTool_bins_35.fa_k141_102792_14,Extracellular matrix glycoprotein Laminin subu...,"KOG0994, Extracellular matrix glycoprotein Lam...",KOG0994,CDD:228940,CELLULAR PROCESSES AND SIGNALING,Extracellular structures
23,SLG1007_DASTool_bins_35.fa_k141_102792_16,Beta-galactosidase/beta-glucuronidase,Beta-galactosidase/beta-glucuronidase [Carbohy...,COG3250,CDD:442481,METABOLISM,Carbohydrate transport and metabolism
24,SLG1007_DASTool_bins_35.fa_k141_102792_16,Beta-galactosidase/beta-glucuronidase,Beta-galactosidase/beta-glucuronidase [Carbohy...,COG3250,CDD:442481,METABOLISM,Carbohydrate transport and metabolism
35,SLG1007_DASTool_bins_35.fa_k141_102792_17,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034,-,-
36,SLG1007_DASTool_bins_35.fa_k141_102792_17,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034,-,-
37,SLG1007_DASTool_bins_35.fa_k141_102792_17,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034,-,-
47,SLG1007_DASTool_bins_35.fa_k141_102792_19,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034,-,-
48,SLG1007_DASTool_bins_35.fa_k141_102792_19,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034,-,-
49,SLG1007_DASTool_bins_35.fa_k141_102792_19,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034,-,-
100,SLG1007_DASTool_bins_35.fa_k141_102792_4,ATPase component of ABC transporters with dupl...,"KOG0062, ATPase component of ABC transporters ...",KOG0062,CDD:228013,METABOLISM,Amino acid transport and metabolism
101,SLG1007_DASTool_bins_35.fa_k141_102792_4,ATPase component of ABC transporters with dupl...,"KOG0062, ATPase component of ABC transporters ...",KOG0062,CDD:228013,METABOLISM,Amino acid transport and metabolism
90,SLG1007_DASTool_bins_35.fa_k141_102792_4,Multidrug resistance-associated protein/mitoxa...,"KOG0054, Multidrug resistance-associated prote...",KOG0054,CDD:228005,METABOLISM,"Secondary metabolites biosynthesis, transport ..."
91,SLG1007_DASTool_bins_35.fa_k141_102792_4,Multidrug resistance-associated protein/mitoxa...,"KOG0054, Multidrug resistance-associated prote...",KOG0054,CDD:228005,METABOLISM,"Secondary metabolites biosynthesis, transport ..."
92,SLG1007_DASTool_bins_35.fa_k141_102792_4,"Multidrug/pheromone exporter, ABC superfamily","KOG0055, Multidrug/pheromone exporter, ABC sup...",KOG0055,CDD:228006,METABOLISM,"Secondary metabolites biosynthesis, transport ..."
93,SLG1007_DASTool_bins_35.fa_k141_102792_4,"Multidrug/pheromone exporter, ABC superfamily","KOG0055, Multidrug/pheromone exporter, ABC sup...",KOG0055,CDD:228006,METABOLISM,"Secondary metabolites biosynthesis, transport ..."

In [9]:
# Filter COG table with only the required genes
need = set(df_exploded["gene_id_single"].dropna().unique())
df_cog = df_cog[df_cog["gene_id_single"].isin(need)].copy()
df_cog

,qseqid,DB ID,Protein description,DB description,CDD ID,General functional category,Functional category,gene_id_single
20834,SLG1007_DASTool_bins_61.fa_k141_12638_90_#_870...,pfam12645,helix-turn-helix domain-containing protein,Helix-turn-helix domain. This domain appears t...,CDD:463654,-,-,SLG1007_DASTool_bins_61.fa_k141_12638_90
20835,SLG1007_DASTool_bins_61.fa_k141_12638_91_#_871...,COG1595,DNA-directed RNA polymerase specialized sigma ...,DNA-directed RNA polymerase specialized sigma ...,CDD:441203,INFORMATION STORAGE AND PROCESSING,Transcription,SLG1007_DASTool_bins_61.fa_k141_12638_91
20836,SLG1007_DASTool_bins_61.fa_k141_12638_91_#_871...,COG1595,DNA-directed RNA polymerase specialized sigma ...,DNA-directed RNA polymerase specialized sigma ...,CDD:441203,INFORMATION STORAGE AND PROCESSING,Transcription,SLG1007_DASTool_bins_61.fa_k141_12638_91
20837,SLG1007_DASTool_bins_61.fa_k141_12638_91_#_871...,PRK09638,RNA polymerase sigma factor SigY,RNA polymerase sigma factor SigY; Reviewed,CDD:182010,-,-,SLG1007_DASTool_bins_61.fa_k141_12638_91
20838,SLG1007_DASTool_bins_61.fa_k141_12638_91_#_871...,TIGR02937,sigma-70 family RNA polymerase sigma factor,"RNA polymerase sigma factor, sigma-70 family. ...",CDD:274357,-,-,SLG1007_DASTool_bins_61.fa_k141_12638_91
...,...,...,...,...,...,...,...,...
2679997,SLG992_DASTool_bins_86.fa_k141_88583_22_#_2052...,COG1961,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,CDD:441564,INFORMATION STORAGE AND PROCESSING,"Replication, recombination and repair",SLG992_DASTool_bins_86.fa_k141_88583_22
2679998,SLG992_DASTool_bins_86.fa_k141_88583_22_#_2052...,PRK12269,-,bifunctional cytidylate kinase/ribosomal prote...,CDD:105491,-,-,SLG992_DASTool_bins_86.fa_k141_88583_22
2679999,SLG992_DASTool_bins_86.fa_k141_88583_22_#_2052...,cd03770,-,"Serine Recombinase (SR) family, TndX-like tran...",CDD:239739,-,-,SLG992_DASTool_bins_86.fa_k141_88583_22
2680000,SLG992_DASTool_bins_86.fa_k141_88583_22_#_2052...,pfam00239,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",CDD:425548,-,-,SLG992_DASTool_bins_86.fa_k141_88583_22
2680001,SLG992_DASTool_bins_86.fa_k141_88583_22_#_2052...,smart00857,"Resolvase, N terminal domain","Resolvase, N terminal domain. The N-terminal d...",CDD:214861,-,-,SLG992_DASTool_bins_86.fa_k141_88583_22

In [10]:
# (Optional but recommended) drop exact duplicate annotation rows per gene
df_cog = df_cog.drop_duplicates(subset=["gene_id_single"] + annot_cols)

# Aggregate to one row per gene (comma-separated lists)
cog_agg = (
    df_cog.groupby("gene_id_single", sort=False, as_index=False)[annot_cols]
          .agg(lambda s: ", ".join(s.tolist()))
)
cog_agg

,gene_id_single,Protein description,DB description,DB ID,CDD ID,General functional category,Functional category
0,SLG1007_DASTool_bins_61.fa_k141_12638_90,helix-turn-helix domain-containing protein,Helix-turn-helix domain. This domain appears t...,pfam12645,CDD:463654,-,-
1,SLG1007_DASTool_bins_61.fa_k141_12638_91,DNA-directed RNA polymerase specialized sigma ...,DNA-directed RNA polymerase specialized sigma ...,"COG1595, PRK09638, TIGR02937, cl22867, pfam04545","CDD:441203, CDD:182010, CDD:274357, CDD:473985...","INFORMATION STORAGE AND PROCESSING, -, -, -, -","Transcription , -, -, -, -"
2,SLG1007_DASTool_bins_61.fa_k141_12638_93,"SAM-dependent methyltransferase, SAM-dependent...",SAM-dependent methyltransferase [Secondary met...,"COG0500, COG0500, cd02440, pfam13649","CDD:440266, CDD:440266, CDD:100107, CDD:463945","METABOLISM, POORLY CHARACTERIZED, -, -","Secondary metabolites biosynthesis, transport ..."
3,SLG1007_DASTool_bins_61.fa_k141_149131_3,-,Family of unknown function (DUF6070). This fam...,pfam19546,CDD:437378,-,-
4,SLG1007_DASTool_bins_61.fa_k141_15629_25,"Predicted ATPase of the ABC class, Predicted A...",Predicted ATPase of the ABC class [General fun...,"COG3044, pfam09818, pfam20446","CDD:442278, CDD:462914, CDD:466595","POORLY CHARACTERIZED, -, -","General function prediction only , -, -"
...,...,...,...,...,...,...,...
23813,SLG992_DASTool_bins_86.fa_k141_74187_1,-,DDE superfamily endonuclease. This family of p...,cl41998,CDD:455343,-,-
23814,SLG992_DASTool_bins_86.fa_k141_74926_2,"ABC-type multidrug transport system, ATPase co...","ABC-type multidrug transport system, ATPase co...","COG1131, KOG0059, KOG0062, KOG0066, KOG0927, P...","CDD:440746, CDD:228010, CDD:228013, CDD:228017...","CELLULAR PROCESSES AND SIGNALING, METABOLISM, ...","Defense mechanisms , Lipid transport and metab..."
23815,SLG992_DASTool_bins_86.fa_k141_85859_10,DKNYY domain-containing protein,DKNYY family. This family represents a group o...,pfam13644,CDD:404523,-,-
23816,SLG992_DASTool_bins_86.fa_k141_85859_13,DUF4304 domain-containing protein,Domain of unknown function (DUF4304). This fam...,pfam14137,CDD:433744,-,-
23817,SLG992_DASTool_bins_86.fa_k141_88583_22,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,"COG1961, PRK12269, cd03770, pfam00239, smart00857","CDD:441564, CDD:105491, CDD:239739, CDD:425548...","INFORMATION STORAGE AND PROCESSING, -, -, -, -","Replication, recombination and repair , -, -, ..."

In [11]:
# ----------------------------
# Merge annotations onto exploded p-value table
# ----------------------------
df_exploded_annot = df_exploded.merge(cog_agg, on="gene_id_single", how="left")

# If you prefer, drop the original gene_id column (which may contain comma-separated genes)
# df_exploded_annot = df_exploded_annot.drop(columns=["gene_id"])
df_exploded_annot.to_csv("/scratch/gpfs/AMOELLER/sidd/diet_manip/p_value_summary_reCOGnizer.tsv", sep="\t", index=False)
df_exploded_annot

,period,mag_id,contig,position,gene_id,test_type,min_p_value,source_file,q_value,gene_id_single,Protein description,DB description,DB ID,CDD ID,General functional category,Functional category
0,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18893,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.214371,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.407921,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
1,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18917,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.224986,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.419240,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
2,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18896,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.183175,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.377877,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
3,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18941,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.733013,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.803778,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
4,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18932,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.398779,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.514322,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333801,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2645,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.152674,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.356860,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333802,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2314,SLG1207_DASTool_bins_18.fa_k141_95558_3,two_sample_paired_tTest,0.197400,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.390277,SLG1207_DASTool_bins_18.fa_k141_95558_3,SusC/RagA family TonB-linked outer membrane pr...,"TonB-linked outer membrane protein, SusC/RagA ...","TIGR04056, cl21470","CDD:274948, CDD:473874","-, -","-, -"
333803,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2575,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.235670,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.430836,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333804,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2643,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.223203,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.417333,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333805,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2581,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.350617,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.466342,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [12]:
df_exploded_annot.head(n=10)

,period,mag_id,contig,position,gene_id,test_type,min_p_value,source_file,q_value,gene_id_single,Protein description,DB description,DB ID,CDD ID,General functional category,Functional category
0,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18893,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.214371,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.407921,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
1,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18917,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.224986,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.419240,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
2,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18896,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.183175,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.377877,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
3,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18941,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.733013,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.803778,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
4,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18932,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.398779,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.514322,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
5,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18943,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.094406,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.266009,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
6,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,19019,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.163666,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.372970,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
7,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,19025,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.161661,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.370115,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,"IS256 family transposase, -",IS256 family transposase. Members of this fami...,"NF033543, cl27632","CDD:468074, CDD:474953","-, -","-, -"
8,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_10730,801,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_107...,two_sample_paired_tTest,0.006129,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.042943,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_107...,"Succinate dehydrogenase/fumarate reductase, fl...","Succinate dehydrogenase/fumarate reductase, fl...","COG1053, cl42162, cl46878","CDD:440673, CDD:455507, CDD:481218","METABOLISM, -, -","Energy production and conversion , -, -"
9,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_10730,786,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_107...,two_sample_paired_tTest,0.002627,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.028622,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_107...,"Succinate dehydrogenase/fumarate reductase, fl...","Succinate dehydrogenase/fumarate reductase, fl...","COG1053, cl42162, cl46878","CDD:440673, CDD:455507, CDD:481218","METABOLISM, -, -","Energy production and conversion , -, -"

In [62]:
df_exploded_annot[df_exploded_annot["Protein description"].isna()]

,period,mag_id,contig,position,gene_id,test_type,min_p_value,source_file,q_value,gene_id_single,Protein description,DB description,DB ID,CDD ID,General functional category,Functional category
245,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398,141,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,two_sample_paired_tTest,0.377683,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.493620,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
246,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398,156,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,two_sample_paired_tTest,0.931943,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.952161,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
250,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398,198,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,two_sample_paired_tTest,0.356735,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.472505,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
252,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398,201,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,two_sample_paired_tTest,0.343665,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.466342,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
253,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398,142,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,two_sample_paired_tTest,0.336365,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.466342,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333798,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2506,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.591092,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.688678,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333801,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2645,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.152674,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.356860,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333803,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2575,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.235670,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.430836,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333804,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2643,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.223203,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.417333,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
333805,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2581,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.350617,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.466342,SLG1207_DASTool_bins_18.fa_k141_95558_4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [14]:
df_cog[df_cog["gene_id_single"]=="SLG1207_DASTool_bins_18.fa_k141_95558_4"]

Empty DataFrame
Columns: [qseqid, DB ID, Protein description, DB description, CDD ID, General functional category, Functional category, gene_id_single]
Index: []

In [15]:
# which genes failed to match annotations?
missing_genes = df_exploded_annot.loc[df_exploded_annot["Protein description"].isna(), "gene_id_single"].unique()
len(missing_genes), missing_genes[:10]

(4315,
 array(['SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398_1',
        'SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398_8',
        'SLG421_DASTool_bins_SLG421_bin.103.fa_k141_287398_7',
        'SLG421_DASTool_bins_SLG421_bin.103.fa_k141_81892_2',
        'SLG1120_DASTool_bins_SLG1120_bin.75.fa_k141_120371_2',
        'SLG1120_DASTool_bins_SLG1120_bin.75.fa_k141_130142_2',
        'SLG1120_DASTool_bins_SLG1120_bin.75.fa_k141_130142_59',
        'SLG1120_DASTool_bins_SLG1120_bin.75.fa_k141_130142_60',
        'SLG1120_DASTool_bins_SLG1120_bin.75.fa_k141_130142_61',
        'SLG1120_DASTool_bins_SLG1120_bin.75.fa_k141_130142_62'],
       dtype=object))

In [16]:
df_exploded_annot["Protein description"].isna().sum()

np.int64(41209)

In [13]:
gene_series

0          SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
1          SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
2          SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
3          SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
4          SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
                                 ...
1501421             SLG1207_DASTool_bins_18.fa_k141_95558_3
1501422             SLG1207_DASTool_bins_18.fa_k141_95558_4
1501423             SLG1207_DASTool_bins_18.fa_k141_95558_4
1501424                                                 <NA>
1501425             SLG1207_DASTool_bins_18.fa_k141_95558_4
Name: gene_id, Length: 393475, dtype: string

# Testing

In [2]:
df_summary=pd.read_csv("/scratch/gpfs/AMOELLER/diet_manip/AlleleFlux_mapq20/longitudinal/p_value_summary/pre_end-fat_control/p_value_summary_two_sample_paired_pre_end.tsv", sep="\t")
df_summary_subset=df_summary[df_summary["test_type"]=="two_sample_paired_tTest"]
df_summary_subset

,period,mag_id,contig,position,gene_id,test_type,min_p_value,source_file,q_value
0,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18893,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.214371,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.407921
1,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18917,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.224986,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.419240
2,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18896,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.183175,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.377877
3,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18941,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.733013,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.803778
4,pre_end,SLG421_DASTool_bins_SLG421_bin.103,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281,18932,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,two_sample_paired_tTest,0.398779,SLG421_DASTool_bins_SLG421_bin.103_two_sample_...,0.514322
...,...,...,...,...,...,...,...,...,...
1501421,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2314,SLG1207_DASTool_bins_18.fa_k141_95558_3,two_sample_paired_tTest,0.197400,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.390277
1501422,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2575,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.235670,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.430836
1501423,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2643,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.223203,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.417333
1501424,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,847,NaN,two_sample_paired_tTest,0.176519,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.374445
1501425,pre_end,SLG1207_DASTool_bins_18,SLG1207_DASTool_bins_18.fa_k141_95558,2581,SLG1207_DASTool_bins_18.fa_k141_95558_4,two_sample_paired_tTest,0.350617,SLG1207_DASTool_bins_18_two_sample_paired.tsv.gz,0.466342

In [3]:
df_cog=pd.read_csv("/scratch/gpfs/AMOELLER/sidd/diet_manip/reCOGnizer_results.tsv",sep="\t")
df_cog

,qseqid,DB ID,Protein description,DB description,EC number,CDD ID,taxonomic_range_name,taxonomic_range,pident,length,...,gapopen,qstart,qend,sstart,send,evalue,bitscore,General functional category,Functional category,KO
0,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,COG1961,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,NaN,CDD:441564,NaN,NaN,25.061,407.0,...,8.0,1.0,405.0,2.0,386.0,3.800000e-63,208.0,INFORMATION STORAGE AND PROCESSING,"Replication, recombination and repair",NaN
1,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,NF041201,NaN,fdxN element excision recombinase XisF.,NaN,CDD:469105,NaN,NaN,21.918,511.0,...,27.0,3.0,483.0,1.0,461.0,7.800000e-29,117.0,NaN,NaN,NaN
2,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,cd00338,NaN,"Serine Recombinase family, catalytic domain; a...",NaN,CDD:238206,NaN,NaN,36.296,135.0,...,1.0,5.0,138.0,1.0,135.0,6.360000e-36,128.0,NaN,NaN,NaN
3,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam00239,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",NaN,CDD:425548,cellular organisms,131567.0,32.215,149.0,...,4.0,3.0,150.0,1.0,144.0,4.200000e-35,126.0,NaN,NaN,NaN
4,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam07508,recombinase family protein,Recombinase. This domain is usually found asso...,NaN,CDD:429502,cellular organisms,131567.0,34.259,108.0,...,2.0,171.0,278.0,1.0,102.0,1.610000e-21,87.5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2680298,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,TIGR00521,bifunctional phosphopantothenoylcysteine decar...,phosphopantothenoylcysteine decarboxylase / ph...,"4.1.1.36,6.3.2.5",CDD:273116,cellular organisms,131567.0,44.784,393.0,...,5.0,2.0,392.0,1.0,390.0,1.010000e-147,421.0,NaN,NaN,NaN
2680299,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam02441,Flavoprotein (Provisional),Flavoprotein. This family contains diverse fla...,NaN,CDD:426775,cellular organisms,131567.0,33.508,191.0,...,4.0,5.0,176.0,1.0,174.0,6.160000e-40,138.0,NaN,NaN,NaN
2680300,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam04127,DNA / pantothenate metabolism flavoprotein (Pr...,DNA / pantothenate metabolism flavoprotein. Th...,NaN,CDD:461186,cellular organisms,131567.0,60.870,184.0,...,2.0,185.0,366.0,1.0,183.0,2.100000e-100,294.0,NaN,NaN,NaN
2680301,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,COG4684,Uncharacterized membrane protein,Uncharacterized membrane protein [Function unk...,NaN,CDD:443720,NaN,NaN,47.000,200.0,...,1.0,1.0,200.0,1.0,193.0,6.860000e-65,196.0,POORLY CHARACTERIZED,Function unknown,NaN
2680302,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,pfam12822,ECF transporter S component,"ECF transporter, substrate-specific component....",NaN,CDD:432808,cellular organisms,131567.0,24.731,186.0,...,4.0,11.0,195.0,3.0,156.0,1.280000e-04,39.2,NaN,NaN,NaN

In [4]:
df_cog["gene_id"] = df_cog["qseqid"].str.split("_#", n=1).str[0]
df_cog

,qseqid,DB ID,Protein description,DB description,EC number,CDD ID,taxonomic_range_name,taxonomic_range,pident,length,...,qstart,qend,sstart,send,evalue,bitscore,General functional category,Functional category,KO,gene_id
0,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,COG1961,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,NaN,CDD:441564,NaN,NaN,25.061,407.0,...,1.0,405.0,2.0,386.0,3.800000e-63,208.0,INFORMATION STORAGE AND PROCESSING,"Replication, recombination and repair",NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
1,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,NF041201,NaN,fdxN element excision recombinase XisF.,NaN,CDD:469105,NaN,NaN,21.918,511.0,...,3.0,483.0,1.0,461.0,7.800000e-29,117.0,NaN,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
2,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,cd00338,NaN,"Serine Recombinase family, catalytic domain; a...",NaN,CDD:238206,NaN,NaN,36.296,135.0,...,5.0,138.0,1.0,135.0,6.360000e-36,128.0,NaN,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
3,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam00239,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",NaN,CDD:425548,cellular organisms,131567.0,32.215,149.0,...,3.0,150.0,1.0,144.0,4.200000e-35,126.0,NaN,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
4,SLG1007_DASTool_bins_35.fa_k141_102792_11_#_10...,pfam07508,recombinase family protein,Recombinase. This domain is usually found asso...,NaN,CDD:429502,cellular organisms,131567.0,34.259,108.0,...,171.0,278.0,1.0,102.0,1.610000e-21,87.5,NaN,NaN,NaN,SLG1007_DASTool_bins_35.fa_k141_102792_11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2680298,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,TIGR00521,bifunctional phosphopantothenoylcysteine decar...,phosphopantothenoylcysteine decarboxylase / ph...,"4.1.1.36,6.3.2.5",CDD:273116,cellular organisms,131567.0,44.784,393.0,...,2.0,392.0,1.0,390.0,1.010000e-147,421.0,NaN,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_8
2680299,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam02441,Flavoprotein (Provisional),Flavoprotein. This family contains diverse fla...,NaN,CDD:426775,cellular organisms,131567.0,33.508,191.0,...,5.0,176.0,1.0,174.0,6.160000e-40,138.0,NaN,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_8
2680300,SLG992_DASTool_bins_86.fa_k141_9710_8_#_8457_#...,pfam04127,DNA / pantothenate metabolism flavoprotein (Pr...,DNA / pantothenate metabolism flavoprotein. Th...,NaN,CDD:461186,cellular organisms,131567.0,60.870,184.0,...,185.0,366.0,1.0,183.0,2.100000e-100,294.0,NaN,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_8
2680301,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,COG4684,Uncharacterized membrane protein,Uncharacterized membrane protein [Function unk...,NaN,CDD:443720,NaN,NaN,47.000,200.0,...,1.0,200.0,1.0,193.0,6.860000e-65,196.0,POORLY CHARACTERIZED,Function unknown,NaN,SLG992_DASTool_bins_86.fa_k141_9710_9
2680302,SLG992_DASTool_bins_86.fa_k141_9710_9_#_10150_...,pfam12822,ECF transporter S component,"ECF transporter, substrate-specific component....",NaN,CDD:432808,cellular organisms,131567.0,24.731,186.0,...,11.0,195.0,3.0,156.0,1.280000e-04,39.2,NaN,NaN,NaN,SLG992_DASTool_bins_86.fa_k141_9710_9

In [6]:
cols_to_use=["gene_id", "Protein description", "DB description", "DB ID", "CDD ID"]
df_cog_subset=df_cog[cols_to_use]
df_cog_subset

,gene_id,Protein description,DB description,DB ID,CDD ID
0,SLG1007_DASTool_bins_35.fa_k141_102792_11,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,COG1961,CDD:441564
1,SLG1007_DASTool_bins_35.fa_k141_102792_11,NaN,fdxN element excision recombinase XisF.,NF041201,CDD:469105
2,SLG1007_DASTool_bins_35.fa_k141_102792_11,NaN,"Serine Recombinase family, catalytic domain; a...",cd00338,CDD:238206
3,SLG1007_DASTool_bins_35.fa_k141_102792_11,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",pfam00239,CDD:425548
4,SLG1007_DASTool_bins_35.fa_k141_102792_11,recombinase family protein,Recombinase. This domain is usually found asso...,pfam07508,CDD:429502
...,...,...,...,...,...
2680298,SLG992_DASTool_bins_86.fa_k141_9710_8,bifunctional phosphopantothenoylcysteine decar...,phosphopantothenoylcysteine decarboxylase / ph...,TIGR00521,CDD:273116
2680299,SLG992_DASTool_bins_86.fa_k141_9710_8,Flavoprotein (Provisional),Flavoprotein. This family contains diverse fla...,pfam02441,CDD:426775
2680300,SLG992_DASTool_bins_86.fa_k141_9710_8,DNA / pantothenate metabolism flavoprotein (Pr...,DNA / pantothenate metabolism flavoprotein. Th...,pfam04127,CDD:461186
2680301,SLG992_DASTool_bins_86.fa_k141_9710_9,Uncharacterized membrane protein,Uncharacterized membrane protein [Function unk...,COG4684,CDD:443720
2680302,SLG992_DASTool_bins_86.fa_k141_9710_9,ECF transporter S component,"ECF transporter, substrate-specific component....",pfam12822,CDD:432808

In [14]:
# Columns you want to aggregate (the 4 annotation columns)
annot_cols = ["Protein description", "DB description", "DB ID", "CDD ID"]
placeholder = "-"   # use "" if you truly want blank, but "-" is usually clearer

df_summary_subset["gene_id"] = df_summary_subset["gene_id"].astype(str).str.strip()
df_cog_subset["gene_id"]     = df_cog_subset["gene_id"].astype(str).str.strip()

need_genes = set(df_summary_subset["gene_key"].dropna().unique())
cog = df_cog_subset[df_cog_subset["gene_key"].isin(need_genes)].copy()

/tmp/ipykernel_3973966/1440745049.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_summary_subset["gene_key"] = df_summary_subset["gene_id"].astype(str).str.strip()
/tmp/ipykernel_3973966/1440745049.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cog_subset["gene_key"]     = df_cog_subset["gene_id"].astype(str).str.strip()

165549

In [15]:
cog

,gene_id,Protein description,DB description,DB ID,CDD ID,gene_key
20834,SLG1007_DASTool_bins_61.fa_k141_12638_90,helix-turn-helix domain-containing protein,Helix-turn-helix domain. This domain appears t...,pfam12645,CDD:463654,SLG1007_DASTool_bins_61.fa_k141_12638_90
20835,SLG1007_DASTool_bins_61.fa_k141_12638_91,DNA-directed RNA polymerase specialized sigma ...,DNA-directed RNA polymerase specialized sigma ...,COG1595,CDD:441203,SLG1007_DASTool_bins_61.fa_k141_12638_91
20836,SLG1007_DASTool_bins_61.fa_k141_12638_91,DNA-directed RNA polymerase specialized sigma ...,DNA-directed RNA polymerase specialized sigma ...,COG1595,CDD:441203,SLG1007_DASTool_bins_61.fa_k141_12638_91
20837,SLG1007_DASTool_bins_61.fa_k141_12638_91,RNA polymerase sigma factor SigY,RNA polymerase sigma factor SigY; Reviewed,PRK09638,CDD:182010,SLG1007_DASTool_bins_61.fa_k141_12638_91
20838,SLG1007_DASTool_bins_61.fa_k141_12638_91,sigma-70 family RNA polymerase sigma factor,"RNA polymerase sigma factor, sigma-70 family. ...",TIGR02937,CDD:274357,SLG1007_DASTool_bins_61.fa_k141_12638_91
...,...,...,...,...,...,...
2679997,SLG992_DASTool_bins_86.fa_k141_88583_22,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,COG1961,CDD:441564,SLG992_DASTool_bins_86.fa_k141_88583_22
2679998,SLG992_DASTool_bins_86.fa_k141_88583_22,NaN,bifunctional cytidylate kinase/ribosomal prote...,PRK12269,CDD:105491,SLG992_DASTool_bins_86.fa_k141_88583_22
2679999,SLG992_DASTool_bins_86.fa_k141_88583_22,NaN,"Serine Recombinase (SR) family, TndX-like tran...",cd03770,CDD:239739,SLG992_DASTool_bins_86.fa_k141_88583_22
2680000,SLG992_DASTool_bins_86.fa_k141_88583_22,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",pfam00239,CDD:425548,SLG992_DASTool_bins_86.fa_k141_88583_22
2680001,SLG992_DASTool_bins_86.fa_k141_88583_22,"Resolvase, N terminal domain","Resolvase, N terminal domain. The N-terminal d...",smart00857,CDD:214861,SLG992_DASTool_bins_86.fa_k141_88583_22

In [18]:
# Make missing values explicit so joins don't "skip" them
for c in annot_cols:
    cog[c] = cog[c].fillna(placeholder)
    cog[c] = cog[c].replace("", placeholder)  # treat empty strings as missing too

# OPTIONAL: drop exact duplicate hit-rows (keeps alignment because it's row-level)
cog = cog.drop_duplicates(subset=["gene_id"] + annot_cols)
cog

/tmp/ipykernel_3973966/4022339348.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cog[c] = cog[c].fillna(placeholder)
/tmp/ipykernel_3973966/4022339348.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cog[c] = cog[c].replace("", placeholder)  # treat empty strings as missing too

,gene_id,Protein description,DB description,DB ID,CDD ID,gene_key
20834,SLG1007_DASTool_bins_61.fa_k141_12638_90,helix-turn-helix domain-containing protein,Helix-turn-helix domain. This domain appears t...,pfam12645,CDD:463654,SLG1007_DASTool_bins_61.fa_k141_12638_90
20835,SLG1007_DASTool_bins_61.fa_k141_12638_91,DNA-directed RNA polymerase specialized sigma ...,DNA-directed RNA polymerase specialized sigma ...,COG1595,CDD:441203,SLG1007_DASTool_bins_61.fa_k141_12638_91
20837,SLG1007_DASTool_bins_61.fa_k141_12638_91,RNA polymerase sigma factor SigY,RNA polymerase sigma factor SigY; Reviewed,PRK09638,CDD:182010,SLG1007_DASTool_bins_61.fa_k141_12638_91
20838,SLG1007_DASTool_bins_61.fa_k141_12638_91,sigma-70 family RNA polymerase sigma factor,"RNA polymerase sigma factor, sigma-70 family. ...",TIGR02937,CDD:274357,SLG1007_DASTool_bins_61.fa_k141_12638_91
20839,SLG1007_DASTool_bins_61.fa_k141_12638_91,-,N/A. Region 4 of sigma-70 like sigma-factors a...,cl22867,CDD:473985,SLG1007_DASTool_bins_61.fa_k141_12638_91
...,...,...,...,...,...,...
2679997,SLG992_DASTool_bins_86.fa_k141_88583_22,Site-specific DNA recombinase SpoIVCA/DNA inve...,Site-specific DNA recombinase SpoIVCA/DNA inve...,COG1961,CDD:441564,SLG992_DASTool_bins_86.fa_k141_88583_22
2679998,SLG992_DASTool_bins_86.fa_k141_88583_22,-,bifunctional cytidylate kinase/ribosomal prote...,PRK12269,CDD:105491,SLG992_DASTool_bins_86.fa_k141_88583_22
2679999,SLG992_DASTool_bins_86.fa_k141_88583_22,-,"Serine Recombinase (SR) family, TndX-like tran...",cd03770,CDD:239739,SLG992_DASTool_bins_86.fa_k141_88583_22
2680000,SLG992_DASTool_bins_86.fa_k141_88583_22,recombinase family protein,"Resolvase, N terminal domain. The N-terminal d...",pfam00239,CDD:425548,SLG992_DASTool_bins_86.fa_k141_88583_22
2680001,SLG992_DASTool_bins_86.fa_k141_88583_22,"Resolvase, N terminal domain","Resolvase, N terminal domain. The N-terminal d...",smart00857,CDD:214861,SLG992_DASTool_bins_86.fa_k141_88583_22

In [21]:
annot_cols = ["Protein description", "DB description", "DB ID", "CDD ID"]
placeholder = "-"

# start from a clean copy
cog_pre = df_cog_subset.copy()

# fill missing (this is the state you actually deduplicate on)
for c in annot_cols:
    cog_pre.loc[:, c] = cog_pre[c].fillna(placeholder).replace("", placeholder)

# Rows that drop_duplicates(keep="first") will remove:
to_drop = cog_pre.duplicated(subset=["gene_id"] + annot_cols, keep="first")
print("rows before:", len(cog_pre))
print("rows that would be dropped:", int(to_drop.sum()))
print("rows after:", len(cog_pre) - int(to_drop.sum()))

# Show the duplicate groups (all copies)
dups_all = (
    cog_pre.loc[cog_pre.duplicated(subset=["gene_id"] + annot_cols, keep=False),
                ["gene_id"] + annot_cols]
          .sort_values(["gene_id"] + annot_cols)
)
dups_all.head(50)

rows before: 2680303
rows that would be dropped: 491394
rows after: 2188909

,gene_id,Protein description,DB description,DB ID,CDD ID
50,SLG1007_DASTool_bins_35.fa_k141_102792_1,"DNA-binding response regulator, OmpR family, c...","DNA-binding response regulator, OmpR family, c...",COG0745,CDD:440508
51,SLG1007_DASTool_bins_35.fa_k141_102792_1,"DNA-binding response regulator, OmpR family, c...","DNA-binding response regulator, OmpR family, c...",COG0745,CDD:440508
14,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250
15,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250
16,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250
17,SLG1007_DASTool_bins_35.fa_k141_102792_14,-,"Methyl-accepting chemotaxis protein (MCP), sig...",cl46910,CDD:481250
11,SLG1007_DASTool_bins_35.fa_k141_102792_14,Extracellular matrix glycoprotein Laminin subu...,"KOG0994, Extracellular matrix glycoprotein Lam...",KOG0994,CDD:228940
12,SLG1007_DASTool_bins_35.fa_k141_102792_14,Extracellular matrix glycoprotein Laminin subu...,"KOG0994, Extracellular matrix glycoprotein Lam...",KOG0994,CDD:228940
19,SLG1007_DASTool_bins_35.fa_k141_102792_15,"Stage III sporulation protein SpoIIID, transcr...","Stage III sporulation protein SpoIIID, transcr...",COG5830,CDD:444532
20,SLG1007_DASTool_bins_35.fa_k141_102792_15,"Stage III sporulation protein SpoIIID, transcr...","Stage III sporulation protein SpoIIID, transcr...",COG5830,CDD:444532
23,SLG1007_DASTool_bins_35.fa_k141_102792_16,Beta-galactosidase/beta-glucuronidase,Beta-galactosidase/beta-glucuronidase [Carbohy...,COG3250,CDD:442481
24,SLG1007_DASTool_bins_35.fa_k141_102792_16,Beta-galactosidase/beta-glucuronidase,Beta-galactosidase/beta-glucuronidase [Carbohy...,COG3250,CDD:442481
35,SLG1007_DASTool_bins_35.fa_k141_102792_17,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034
36,SLG1007_DASTool_bins_35.fa_k141_102792_17,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034
37,SLG1007_DASTool_bins_35.fa_k141_102792_17,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034
38,SLG1007_DASTool_bins_35.fa_k141_102792_18,Hydroxymethylpyrimidine pyrophosphatase and ot...,Hydroxymethylpyrimidine pyrophosphatase and ot...,COG0561,CDD:440327
39,SLG1007_DASTool_bins_35.fa_k141_102792_18,Hydroxymethylpyrimidine pyrophosphatase and ot...,Hydroxymethylpyrimidine pyrophosphatase and ot...,COG0561,CDD:440327
47,SLG1007_DASTool_bins_35.fa_k141_102792_19,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034
48,SLG1007_DASTool_bins_35.fa_k141_102792_19,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034
49,SLG1007_DASTool_bins_35.fa_k141_102792_19,-,Glycosyl hydrolases. This is a family of bacte...,cl23725,CDD:474034
100,SLG1007_DASTool_bins_35.fa_k141_102792_4,ATPase component of ABC transporters with dupl...,"KOG0062, ATPase component of ABC transporters ...",KOG0062,CDD:228013
101,SLG1007_DASTool_bins_35.fa_k141_102792_4,ATPase component of ABC transporters with dupl...,"KOG0062, ATPase component of ABC transporters ...",KOG0062,CDD:228013
90,SLG1007_DASTool_bins_35.fa_k141_102792_4,Multidrug resistance-associated protein/mitoxa...,"KOG0054, Multidrug resistance-associated prote...",KOG0054,CDD:228005
91,SLG1007_DASTool_bins_35.fa_k141_102792_4,Multidrug resistance-associated protein/mitoxa...,"KOG0054, Multidrug resistance-associated prote...",KOG0054,CDD:228005
92,SLG1007_DASTool_bins_35.fa_k141_102792_4,"Multidrug/pheromone exporter, ABC superfamily","KOG0055, Multidrug/pheromone exporter, ABC sup...",KOG0055,CDD:228006
93,SLG1007_DASTool_bins_35.fa_k141_102792_4,"Multidrug/pheromone exporter, ABC superfamily","KOG0055, Multidrug/pheromone exporter, ABC sup...",KOG0055,CDD:228006
104,SLG1007_DASTool_bins_35.fa_k141_102792_4,Pleiotropic drug resistance proteins (PDR1-15)...,"KOG0065, Pleiotropic drug resistance proteins ...",KOG0065,CDD:228016
105,SLG1007_DASTool_bins_35.fa_k141_102792_4,Pleiotropic drug resistance proteins (PDR1-15)...,"KOG0065, Pleiotropic drug resistance proteins ...",KOG0065,CDD:228016
108,SLG1007_DASTool_bins_35.fa_k141_102792_4,Predicted transporter (ABC superfamily),"KOG0927, Predicted transporter (ABC superfamil...",KOG0927,CDD:228873
109,SLG1007_DASTool_bins_35.fa_k141_102792_4,Predicted transporter (ABC superfamily),"KOG0927, Predicted transporter (ABC superfamil...",KOG0927,CDD:228873
106,SLG1007_DASTool_bins_35.fa_k141_102792_4,eIF2-interacting protein ABC50 (ABC superfamily),"KOG0066, eIF2-interacting protein ABC50 (ABC s...",KOG0066,CDD:228017
107,SLG1007_DASTool_bins_35.fa_k141_102792_4,eIF2-interacting protein ABC50 (ABC superfamily),"KOG0066, eIF2-interacting protein ABC50 (ABC s...",KOG0066,CDD:228017
124,SLG1007_DASTool_bins_35.fa_k141_102792_6,-,Type 2 periplasmic binding fold superfamily. T...,cl21456,CDD:473866
125,SLG1007_DASTool_bins_35.fa_k141_102792_6,-,Type 2 periplasmic binding fold superfamily. T...,cl21456,CDD:473866
126,SLG1007_DASTool_bins_35.fa_k141_102792_6,-,Type 2 periplasmic binding fold superfamily. T...,cl21456,CDD:473866
132,SLG1007_DASTool_bins_35.fa_k141_102792_7,-,N/A. This is a putative pyridoxal 5'-phosphate...,cl18945,CDD:450240
133,SLG1007_DASTool_bins_35.fa_k141_102792_7,-,N/A. This is a putative pyridoxal 5'-phosphate...,cl18945,CDD:450240
134,SLG1007_DASTool_bins_35.fa_k141_102792_7,-,N/A. This is a putative pyridoxal 5'-phosphate...,cl18945,CDD:450240
195,SLG1007_DASTool_bins_35.fa_k141_105139_1,-,N/A. This family of proteins are related to th...,cl00195,CDD:444738
196,SLG1007_DASTool_bins_35.fa_k141_105139_1,-,N/A. This family of proteins are related to th...,cl00195,CDD:444738
192,SLG1007_DASTool_bins_35.fa_k141_105139_1,NAD-dependent protein deacylase,NAD-dependent deacetylase; Provisional,PRK00481,CDD:234777
193,SLG1007_DASTool_bins_35.fa_k141_105139_1,NAD-dependent protein deacylase,NAD-dependent deacetylase; Provisional,PRK00481,CDD:234777
194,SLG1007_DASTool_bins_35.fa_k141_105139_1,NAD-dependent protein deacylase,NAD-dependent deacetylase; Provisional,PRK00481,CDD:234777
162,SLG1007_DASTool_bins_35.fa_k141_105139_15,-,N/A. This is a putative pyridoxal 5'-phosphate...,cl18945,CDD:450240
163,SLG1007_DASTool_bins_35.fa_k141_105139_15,-,N/A. This is a putative pyridoxal 5'-phosphate...,cl18945,CDD:450240
168,SLG1007_DASTool_bins_35.fa_k141_105139_16,-,N/A. This family includes enzymes related to c...,cl17190,CDD:450170
169,SLG1007_DASTool_bins_35.fa_k141_105139_16,-,N/A. This family includes enzymes related to c...,cl17190,CDD:450170
170,SLG1007_DASTool_bins_35.fa_k141_105139_16,-,N/A. This family includes enzymes related to c...,cl17190,CDD:450170
171,SLG1007_DASTool_bins_35.fa_k141_105139_16,-,N/A. This family includes enzymes related to c...,cl17190,CDD:450170
204,SLG1007_DASTool_bins_35.fa_k141_105139_20,-,N/A. This family appears to be a methyltransfe...,cl17173,CDD:473071

In [ ]:

# Aggregate: one row per gene_id, comma-separated lists per column
cog_agg = (
    cog.groupby("gene_id", sort=False, as_index=False)[annot_cols]
       .agg(lambda s: ", ".join(s.tolist()))
)

# Merge onto your summary table (left join keeps all summary rows)
df_merged = df_summary_subset.merge(cog_agg, on="gene_id", how="left")

In [11]:
summary_ids = df_summary_subset["gene_id"].dropna().astype(str).str.strip()
cog_ids     = df_cog_subset["gene_id"].dropna().astype(str).str.strip()

print("example summary:", summary_ids.iloc[0])
print("example cog    :", cog_ids.iloc[0])
print("unique summary:", summary_ids.nunique())
print("unique cog    :", cog_ids.nunique())
print("intersection  :", len(set(summary_ids.unique()) & set(cog_ids.unique())))

example summary: SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105281_23
example cog    : SLG1007_DASTool_bins_35.fa_k141_102792_11
unique summary: 28343
unique cog    : 384604
intersection  : 23793

In [12]:
g = summary_ids.iloc[0]
df_cog[df_cog["qseqid"].astype(str).str.startswith(g, na=False)].head()

,qseqid,DB ID,Protein description,DB description,EC number,CDD ID,taxonomic_range_name,taxonomic_range,pident,length,...,qstart,qend,sstart,send,evalue,bitscore,General functional category,Functional category,KO,gene_id
1292729,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,NF033543,IS256 family transposase,IS256 family transposase. Members of this fami...,NaN,CDD:468074,cellular organisms,131567.0,40.385,104.0,...,28.0,130.0,27.0,129.0,3.500000e-31,112.0,NaN,NaN,NaN,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
1292730,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,cl27632,NaN,"Transposase, Mutator family.",NaN,CDD:474953,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...
1292731,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...,cl27632,NaN,"Transposase, Mutator family.",NaN,CDD:474953,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLG421_DASTool_bins_SLG421_bin.103.fa_k141_105...